"use strict";
const assert = require("node:assert/strict"); const fs = require("node:fs"); const path = require("node:path"); const root = path.resolve(__dirname, "..");
const routes = fs.readFileSync(path.join(root, "routes/api-routes.js"), "utf8"); const source = fs.readFileSync(path.join(root, "controllers/ipadAdminArenaPolicyController.js"), "utf8"); const calls = [];
function install(filename, value) { const resolved = require.resolve(filename); require.cache[resolved] = { id: resolved, filename: resolved, loaded: true, exports: value }; }
const base = { _id: "p1", code: "P1", displayName: "Policy", status: "ACTIVE", effectiveFrom: new Date(), priceAmount: 29000 };
install("../services/arenaPolicyService", { activateArenaPolicyVersion: async (v) => { calls.push(["activateSub", v]); return base; }, activateMainDivisionPolicyVersion: async (v) => { calls.push(["activateMain", v]); return base; }, createArenaPolicyVersion: async (v) => { calls.push(["createSub", v]); return base; }, createMainDivisionPolicyVersion: async (v) => { calls.push(["createMain", v]); return base; }, getArenaPolicyAdminData: async () => ({ paybackRules: { cycleDays: 29, minimumAttackParticipationDays: 15 }, learningPackage: { activePolicy: base, policies: [base] }, sub: { activePolicy: base, upcomingPolicy: null, policies: [base] }, main: { activePolicy: base, upcomingPolicy: null, policies: [base] } }), retireArenaPolicyVersion: async (v) => calls.push(["retireSub", v]), retireMainDivisionPolicyVersion: async (v) => calls.push(["retireMain", v]), updateLearningPackagePrice: async (v) => { calls.push(["learning", v]); return base; } });
install("../services/mockExamPackageService", { getMockExamPackageAdminData: async () => ({ activePolicy: { monthlyPriceAmount: 5500, billingPeriodDays: 30 }, policies: [] }), updateMockExamPackagePrice: async (v) => { calls.push(["mock", v]); return base; } });
install("../services/arenaShopPolicyService", { getMainShopPolicyAdminData: async () => ({ activePolicy: { items: [{ itemCode: "A", displayName: "Item", priceDays: 2, enabled: true }] } }), updateMainShopPolicy: async (v) => { calls.push(["shop", v]); return base; } });
install("../services/arenaMatchmakingControlService", { getMatchmakingControl: async () => ({ isPaused: false }), setMatchmakingPaused: async (v) => calls.push(["matchmaking", v]) });
install("../services/policyChangeNotificationService", { queuePolicyChangeNotifications: async () => ({ queued: 1 }) });
for (const value of ["/admin/arena-policies\"", "/admin/arena-policies/matchmaking", "/admin/arena-policies/learning-package", "/admin/arena-policies/mock-exam", "/admin/arena-policies/shop", "/admin/arena-policies/unranked", "/admin/arena-policies/ranked", "/admin/arena-policies/:division/:policyId/activate", "/admin/arena-policies/:division/:policyId/retire"]) assert(routes.includes(value), `missing ${value}`);
assert(source.includes("req.apiUser")); assert(!source.includes("req.session"));
const controller = require("../controllers/ipadAdminArenaPolicyController");
async function invoke(handler, { role = "admin", params = {}, body = {} } = {}) { let payload; let error; const headers = new Map(); const req = { apiUser: { _id: "507f1f77bcf86cd799439011", role }, params, body }; const res = { set(k, v) { headers.set(k, v); return res; }, json(v) { payload = v; return res; } }; await handler(req, res, (v) => { error = v; }); return { payload, error, headers }; }
(async () => { assert.equal((await invoke(controller.dashboard, { role: "student" })).error?.status, 403); const dashboard = await invoke(controller.dashboard); assert.equal(dashboard.payload.schemaVersion, "ADMIN_ARENA_POLICY_NATIVE_V1"); assert.equal(dashboard.payload.dashboard.learningPackage.active.priceAmount, 29000); await invoke(controller.matchmaking, { body: { action: "PAUSE", reason: "ops" } }); await invoke(controller.learningPrice, { body: { priceAmount: 39000 } }); await invoke(controller.mockPrice, { body: { monthlyPriceAmount: 5500 } }); await invoke(controller.shop, { body: { items: [{ code: "A", priceDays: 3, enabled: true }] } }); await invoke(controller.createUnranked, { body: { displayName: "Sub" } }); await invoke(controller.createRanked, { body: { displayName: "Main" } }); await invoke(controller.activate, { params: { division: "MAIN", policyId: "p1" } }); await invoke(controller.retire, { params: { division: "SUB", policyId: "p1" } }); assert(calls.some(([n]) => n === "matchmaking")); assert(calls.some(([n]) => n === "shop")); assert(calls.some(([n]) => n === "createSub")); assert(calls.some(([n]) => n === "createMain")); assert(calls.some(([n]) => n === "activateMain")); assert(calls.some(([n]) => n === "retireSub")); console.log("iPad native admin Arena policy HTTP contract passed"); })().catch((error) => { console.error(error); process.exitCode = 1; });
