"use strict";
const assert = require("node:assert/strict"); const fs = require("node:fs"); const path = require("node:path"); const root = path.resolve(__dirname, ".."); const routes = fs.readFileSync(path.join(root, "routes/api-routes.js"), "utf8"); const source = fs.readFileSync(path.join(root, "controllers/ipadAdminProblemBankController.js"), "utf8"); const calls = [];
function install(filename, value) { const resolved = require.resolve(filename); require.cache[resolved] = { id: resolved, filename: resolved, loaded: true, exports: value }; }
const validationReport = { passed: true, sampleCount: 5 }; const version = { _id: "v1", code: "V1", displayName: "Version", status: "ACTIVE", validationReport };
install("../services/arenaProblemDataService", { getAdminArenaProblemData: async () => ({ active: version, recent: [version], editable: null, availableTypes: [{ typeId: "A", label: "A" }], difficultyTiers: ["T1"], form: { tierConfigurations: [{ difficultyTier: "T1", typeIds: ["A"] }], typeSettings: [{ typeId: "A" }] } }), createArenaProblemDataDraft: async (v) => { calls.push(["create", v]); return { _id: "v2" }; }, updateArenaProblemDataDraft: async (v) => calls.push(["update", v]), activateArenaProblemDataVersion: async (v) => calls.push(["activate", v]) });
install("../services/problemTypeCatalogService", { getAdminProblemTypeCatalog: async () => ({ categories: [{ key: "CONCEPT_PRACTICE", label: "Concept", count: 1 }], selectedCategory: "CONCEPT_PRACTICE", entries: [{ _id: "t1", category: "CONCEPT_PRACTICE", engineKey: "A", displayName: "A", validationReport }], inspected: null, history: [] }), reviseProblemTypeVersion: async (v) => calls.push(["revise", v]), syncProblemTypeRegistry: async (v) => { calls.push(["sync", v]); return { inserted: [], updated: [], retired: [], total: 1 }; } });
install("../services/arenaTierQuestionCatalogService", { getAdminArenaTierCatalog: async () => ({ active: { ...version, typeDefinitions: [{ typeId: "A", label: "A" }] }, recent: [], publicDifficultyCatalog: [] }), createArenaTierCatalogType: async (v) => calls.push(["tier", v]) });
for (const value of ["/admin/problem-banks\"", "/admin/problem-banks/types/sync", "/admin/problem-banks/types/:versionId/revise", "/admin/problem-banks/arena/types", "/admin/problem-banks/arena/data\"", "/admin/problem-banks/arena/data/:versionId\"", "/admin/problem-banks/arena/data/:versionId/activate"]) assert(routes.includes(value), `missing ${value}`); assert(source.includes("req.apiUser")); assert(!source.includes("req.session"));
const controller = require("../controllers/ipadAdminProblemBankController"); async function invoke(handler, { role = "admin", params = {}, body = {}, query = {} } = {}) { let payload; let error; const req = { apiUser: { _id: "507f1f77bcf86cd799439011", role }, params, body, query }; const res = { set() { return res; }, json(v) { payload = v; return res; } }; await handler(req, res, (v) => { error = v; }); return { payload, error }; }
(async () => { assert.equal((await invoke(controller.dashboard, { role: "student" })).error?.status, 403); const dashboard = await invoke(controller.dashboard); assert.equal(dashboard.payload.schemaVersion, "ADMIN_PROBLEM_BANK_NATIVE_V1"); assert.equal(dashboard.payload.dashboard.problem.active.id, "v1"); await invoke(controller.syncTypes); await invoke(controller.reviseType, { params: { versionId: "t1" } }); await invoke(controller.createTierType); const created = await invoke(controller.createProblemData); assert.equal(created.payload.versionId, "v2"); await invoke(controller.updateProblemData, { params: { versionId: "v2" } }); await invoke(controller.activateProblemData, { params: { versionId: "v2" } }); assert.deepEqual(calls.map(([n]) => n), ["sync", "revise", "tier", "create", "update", "activate"]); console.log("iPad native admin problem bank HTTP contract passed"); })().catch((error) => { console.error(error); process.exitCode = 1; });
