"use strict";

const {
  activateArenaPolicyVersion,
  activateMainDivisionPolicyVersion,
  createArenaPolicyVersion,
  createMainDivisionPolicyVersion,
  getArenaPolicyAdminData,
  retireArenaPolicyVersion,
  retireMainDivisionPolicyVersion,
  updateLearningPackagePrice,
} = require("../services/arenaPolicyService");
const { getMockExamPackageAdminData, updateMockExamPackagePrice } = require("../services/mockExamPackageService");
const { getMainShopPolicyAdminData, updateMainShopPolicy } = require("../services/arenaShopPolicyService");
const { getMatchmakingControl, setMatchmakingPaused } = require("../services/arenaMatchmakingControlService");
const { queuePolicyChangeNotifications } = require("../services/policyChangeNotificationService");

const SCHEMA_VERSION = "ADMIN_ARENA_POLICY_NATIVE_V1";
function requireAdmin(req) { if (String(req.apiUser?.role || "").toLowerCase() !== "admin") { const error = new Error("관리자만 Arena 정책을 변경할 수 있습니다."); error.status = 403; throw error; } return req.apiUser; }
function id(value) { return String(value?._id || value?.id || value || ""); }
function noStore(res) { res.set("Cache-Control", "private, no-store"); }
function policy(value = {}) { return { id: id(value), code: String(value.code || ""), displayName: String(value.displayName || ""), status: String(value.status || ""), effectiveFrom: value.effectiveFrom || null, effectiveUntil: value.effectiveUntil || null, priceAmount: value.priceAmount == null ? null : Number(value.priceAmount), initialLearningDays: value.initialLearningDays == null ? null : Number(value.initialLearningDays), initialPaybackScoreDays: value.initialPaybackScoreDays == null ? null : Number(value.initialPaybackScoreDays), maximumTargetTierGap: value.maximumTargetTierGap == null ? null : Number(value.maximumTargetTierGap), revengeStakeMultiplier: value.revengeStakeMultiplier == null ? null : Number(value.revengeStakeMultiplier), revengeFeeDays: value.revengeFeeDays == null ? null : Number(value.revengeFeeDays), changeSummary: String(value.changeSummary || "") }; }
async function notify(policyType, value) { try { await queuePolicyChangeNotifications({ policyType, policy: value }); } catch (error) { console.error("native policy notification deferred:", error); } }
async function data() { const [arena, mockExamOnly, mainShop, matchmakingControl] = await Promise.all([getArenaPolicyAdminData(), getMockExamPackageAdminData(), getMainShopPolicyAdminData(), getMatchmakingControl()]); return { matchmaking: { isPaused: matchmakingControl?.isPaused === true, reason: String(matchmakingControl?.reason || ""), pausedAt: matchmakingControl?.pausedAt || null }, learningPackage: { active: policy(arena.learningPackage?.activePolicy), policies: (arena.learningPackage?.policies || []).map(policy) }, mockExam: { activePrice: Number(mockExamOnly.activePolicy?.monthlyPriceAmount || 0), billingPeriodDays: Number(mockExamOnly.activePolicy?.billingPeriodDays || 30), policies: (mockExamOnly.policies || []).map((value) => ({ ...policy(value), priceAmount: Number(value.monthlyPriceAmount || 0) })) }, shop: { items: (mainShop.activePolicy?.items || []).map((item) => ({ code: String(item.itemCode || ""), name: String(item.displayName || ""), priceDays: Number(item.priceDays || 0), enabled: item.enabled === true })) }, unranked: { active: policy(arena.sub?.activePolicy), upcoming: arena.sub?.upcomingPolicy ? policy(arena.sub.upcomingPolicy) : null, policies: (arena.sub?.policies || []).map(policy) }, ranked: { active: arena.main?.activePolicy ? policy(arena.main.activePolicy) : null, upcoming: arena.main?.upcomingPolicy ? policy(arena.main.upcomingPolicy) : null, policies: (arena.main?.policies || []).map(policy) }, paybackRules: arena.paybackRules || {} }; }
async function dashboard(res) { noStore(res); return res.json({ schemaVersion: SCHEMA_VERSION, dashboard: await data() }); }
async function action(res) { noStore(res); return res.json({ schemaVersion: SCHEMA_VERSION, ok: true, dashboard: await data() }); }

exports.dashboard = async (req, res, next) => { try { requireAdmin(req); return dashboard(res); } catch (error) { return next(error); } };
exports.matchmaking = async (req, res, next) => { try { const admin = requireAdmin(req); const actionName = String(req.body?.action || "").toUpperCase(); if (!["PAUSE", "RESUME"].includes(actionName)) { const error = new Error("매치메이킹 제어 명령을 확인해주세요."); error.status = 400; throw error; } await setMatchmakingPaused({ adminUserId: admin._id || admin.id, paused: actionName === "PAUSE", reason: req.body?.reason }); return action(res); } catch (error) { return next(error); } };
exports.learningPrice = async (req, res, next) => { try { const admin = requireAdmin(req); const value = await updateLearningPackagePrice({ adminUserId: admin._id || admin.id, priceAmount: req.body?.priceAmount, changeSummary: req.body?.changeSummary }); await notify("LEARNING_PACKAGE", value); return action(res); } catch (error) { return next(error); } };
exports.mockPrice = async (req, res, next) => { try { const admin = requireAdmin(req); const value = await updateMockExamPackagePrice({ adminUserId: admin._id || admin.id, monthlyPriceAmount: req.body?.monthlyPriceAmount, changeSummary: req.body?.changeSummary }); await notify("MOCK_EXAM_PACKAGE", value); return action(res); } catch (error) { return next(error); } };
exports.shop = async (req, res, next) => { try { const admin = requireAdmin(req); const items = Array.isArray(req.body?.items) ? req.body.items : []; const value = await updateMainShopPolicy({ adminUserId: admin._id || admin.id, itemPrices: Object.fromEntries(items.map((item) => [item.code, item.priceDays])), enabledItems: items.filter((item) => item.enabled).map((item) => item.code), changeSummary: req.body?.changeSummary }); await notify("MAIN_SHOP", value); return action(res); } catch (error) { return next(error); } };
exports.createUnranked = async (req, res, next) => { try { const admin = requireAdmin(req); const draft = await createArenaPolicyVersion({ adminUserId: admin._id || admin.id, input: req.body || {} }); const value = await activateArenaPolicyVersion({ adminUserId: admin._id || admin.id, policyId: draft._id }); await notify("SUB_DIVISION", value); return action(res); } catch (error) { return next(error); } };
exports.createRanked = async (req, res, next) => { try { const admin = requireAdmin(req); const draft = await createMainDivisionPolicyVersion({ adminUserId: admin._id || admin.id, input: req.body || {} }); const value = await activateMainDivisionPolicyVersion({ adminUserId: admin._id || admin.id, policyId: draft._id }); await notify("MAIN_DIVISION", value); return action(res); } catch (error) { return next(error); } };
exports.activate = async (req, res, next) => { try { const admin = requireAdmin(req); const ranked = String(req.params.division).toUpperCase() === "MAIN"; const value = ranked ? await activateMainDivisionPolicyVersion({ adminUserId: admin._id || admin.id, policyId: req.params.policyId }) : await activateArenaPolicyVersion({ adminUserId: admin._id || admin.id, policyId: req.params.policyId }); await notify(ranked ? "MAIN_DIVISION" : "SUB_DIVISION", value); return action(res); } catch (error) { return next(error); } };
exports.retire = async (req, res, next) => { try { const admin = requireAdmin(req); const ranked = String(req.params.division).toUpperCase() === "MAIN"; if (ranked) await retireMainDivisionPolicyVersion({ adminUserId: admin._id || admin.id, policyId: req.params.policyId }); else await retireArenaPolicyVersion({ adminUserId: admin._id || admin.id, policyId: req.params.policyId }); return action(res); } catch (error) { return next(error); } };
