"use strict";
const { activateArenaProblemDataVersion, createArenaProblemDataDraft, getAdminArenaProblemData, updateArenaProblemDataDraft } = require("../services/arenaProblemDataService");
const { getAdminProblemTypeCatalog, reviseProblemTypeVersion, syncProblemTypeRegistry } = require("../services/problemTypeCatalogService");
const { createArenaTierCatalogType, getAdminArenaTierCatalog } = require("../services/arenaTierQuestionCatalogService");
const SCHEMA_VERSION = "ADMIN_PROBLEM_BANK_NATIVE_V1";
function requireAdmin(req) { if (String(req.apiUser?.role || "").toLowerCase() !== "admin") { const error = new Error("관리자만 문제 유형과 문제 데이터를 관리할 수 있습니다."); error.status = 403; throw error; } return req.apiUser; }
function id(value) { return String(value?._id || value?.id || value || ""); }
function noStore(res) { res.set("Cache-Control", "private, no-store"); }
function validation(value = {}) { return { passed: value.passed === true, sampleCount: Number(value.sampleCount || 0), validationMode: String(value.validationMode || ""), calculatorFree: value.calculatorFree === true, answerVerified: value.answerVerified === true, failures: (value.failures || []).map((item) => String(item?.message || item)) }; }
function type(value = {}) { return { id: id(value), category: String(value.category || ""), engineKey: String(value.engineKey || ""), displayName: String(value.displayName || value.label || ""), courseId: String(value.courseId || ""), unitId: String(value.unitId || ""), conceptId: String(value.conceptId || ""), enabled: value.enabled !== false, selectionWeight: Number(value.selectionWeight || 1), revision: Number(value.revision || 1), operatorNote: String(value.operatorNote || ""), sourceFile: String(value.sourceFile || ""), sourceSnapshot: String(value.sourceSnapshot || ""), sourceHash: String(value.sourceHash || ""), codeChanged: value.codeChanged === true, validation: validation(value.validationReport) }; }
function version(value = {}) { return { id: id(value), code: String(value.code || ""), displayName: String(value.displayName || ""), status: String(value.status || ""), engineVersion: String(value.engineVersion || ""), changeSummary: String(value.changeSummary || ""), contentHash: String(value.contentHash || ""), activatedAt: value.activatedAt || null, updatedAt: value.updatedAt || null, validation: validation(value.validationReport) }; }
async function data(query = {}) { const [problem, types, tiers] = await Promise.all([getAdminArenaProblemData({ editVersionId: query.editVersionId || "" }), getAdminProblemTypeCatalog({ category: query.category || "CONCEPT_PRACTICE", query: query.query || "", inspectVersionId: query.inspectVersionId || "" }), getAdminArenaTierCatalog()]); return { types: { categories: (types.categories || []).map((item) => ({ key: String(item.key), label: String(item.label || ""), description: String(item.description || ""), count: Number(item.count || 0) })), selectedCategory: String(types.selectedCategory || ""), entries: (types.entries || []).map(type), inspected: types.inspected ? type(types.inspected) : null, history: (types.history || []).map(type) }, problem: { active: version(problem.active), recent: (problem.recent || []).map(version), editableId: id(problem.editable), availableTypes: (problem.availableTypes || []).map((item) => ({ id: String(item.typeId || ""), label: String(item.label || item.typeId || ""), courseId: String(item.courseId || ""), expectedTimeMs: Number(item.expectedTimeMs || 0) })), difficultyTiers: problem.difficultyTiers || [], form: { code: String(problem.form?.code || ""), displayName: String(problem.form?.displayName || ""), changeSummary: String(problem.form?.changeSummary || ""), tierConfigurations: (problem.form?.tierConfigurations || []).map((item) => ({ difficultyTier: String(item.difficultyTier || ""), typeIds: (item.typeIds || []).map(String) })), typeSettings: (problem.form?.typeSettings || []).map((item) => ({ typeId: String(item.typeId || ""), enabled: item.enabled !== false, selectionWeight: Number(item.selectionWeight || 1), answerMin: Number(item.answerMin || 1), answerMax: Number(item.answerMax || 999), difficultyNote: String(item.difficultyNote || "") })) } }, tiers: { active: tiers.active ? version(tiers.active) : null, recent: (tiers.recent || []).map(version), baseTypes: (tiers.active?.typeDefinitions || []).map((item) => ({ id: String(item.typeId || ""), label: String(item.label || item.typeId || "") })), publicDifficultyCatalog: (tiers.publicDifficultyCatalog || []).map((item) => ({ difficultyCode: String(item.difficultyCode || ""), catalogTier: String(item.catalogTier || ""), minimumTypeVariants: Number(item.minimumTypeVariants || 0), variantCount: (item.variantTypes || []).length, packComposition: String(item.packComposition || "") })) } }; }
async function dashboard(res, query = {}) { noStore(res); return res.json({ schemaVersion: SCHEMA_VERSION, dashboard: await data(query) }); }
async function ok(res) { noStore(res); return res.json({ schemaVersion: SCHEMA_VERSION, ok: true }); }
exports.dashboard = async (req, res, next) => { try { requireAdmin(req); return dashboard(res, req.query || {}); } catch (error) { return next(error); } };
exports.syncTypes = async (req, res, next) => { try { const admin = requireAdmin(req); const result = await syncProblemTypeRegistry({ adminUserId: admin._id || admin.id, activateSourceChanges: true }); noStore(res); return res.json({ schemaVersion: SCHEMA_VERSION, ok: true, result }); } catch (error) { return next(error); } };
exports.reviseType = async (req, res, next) => { try { const admin = requireAdmin(req); await reviseProblemTypeVersion({ adminUserId: admin._id || admin.id, versionId: req.params.versionId, input: req.body || {} }); return ok(res); } catch (error) { return next(error); } };
exports.createTierType = async (req, res, next) => { try { const admin = requireAdmin(req); await createArenaTierCatalogType({ adminUserId: admin._id || admin.id, input: req.body || {} }); return ok(res); } catch (error) { return next(error); } };
exports.createProblemData = async (req, res, next) => { try { const admin = requireAdmin(req); const value = await createArenaProblemDataDraft({ adminUserId: admin._id || admin.id, input: req.body || {} }); noStore(res); return res.json({ schemaVersion: SCHEMA_VERSION, ok: true, versionId: id(value) }); } catch (error) { return next(error); } };
exports.updateProblemData = async (req, res, next) => { try { const admin = requireAdmin(req); await updateArenaProblemDataDraft({ adminUserId: admin._id || admin.id, versionId: req.params.versionId, input: req.body || {} }); return ok(res); } catch (error) { return next(error); } };
exports.activateProblemData = async (req, res, next) => { try { const admin = requireAdmin(req); await activateArenaProblemDataVersion({ adminUserId: admin._id || admin.id, versionId: req.params.versionId }); return ok(res); } catch (error) { return next(error); } };
